spring:
  application:
    name: datalog-api
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:5432/datalog_api?schema=datalog_api
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    default-schema: datalog_api
    liquibase-schema: datalog_api
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/datalog_api?schema=datalog_api
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  devtools:
    add-properties: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json