spring:
  application:
    name: obdtrak-api
  liquibase:
    url: jdbc:postgresql://${DB_HOST}:5432/obd_trak?schema=obd_trak
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    default-schema: obd_trak
    liquibase-schema: obd_trak
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/obd_trak?schema=obd_trak
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-7pr07becg7e5y37g.us.auth0.com/
  devtools:
    add-properties: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json