spring:
  liquibase:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS DATALOG_API
    user: sa
    password: sa
    default-schema: datalog_api
    liquibase-schema: datalog_api
  r2dbc:
    url: r2dbc:h2:mem:///db?options=DB_CLOSE_DELAY=-1;SCHEMA=datalog_api
    username: sa
    password: sa
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/default